### ISSUE TITLE
Raspberry Pi Zero Support

### ISSUE THREAD

**Issue by hoseung2** [SKKU-ESLAB/ANT#105]
I'm planning to work with the ANT framework to support **Raspberry Pi Zero**.

To Do
---
- [ ] Sensor data collection
- [ ] Communication with Gateway(Odroid XU4)
- [ ] Verify that the function is working properly

**Comment by RedCarrottt** [comment]
Nice work.

Raspberry Pi Zero is the device easiest to port ANT framework and light-weight as I know.

**Comment by RedCarrottt** [comment]
As sensor plug-ins are deprecated in ANT Lite, there is no need to port sensor plug-ins for Raspberry Pi Zero.
So I close this issue.
