### ISSUE TITLE
Need more ANT apps

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#110]
Currently, ANT has 6 apps.
- CameraViewer
- ImageClassifier
- MotionClassifier
- SensorViewer
- MachineLearning
- QuickCam

All of these are concentrated only on the camera, sensor, and ML sides.
ANT provides various APIs, and I think that we need apps that can handle many APIs.

**Comment by RedCarrottt** [comment]
I added a new example app for Remote UI API, ```RemoteUI```. (PR #125)

**Comment by RedCarrottt** [comment]
As now, we provides example applications for all the APIs, which are provided by ANT.
We added many examples for several years.
So I close this issue.
