### ISSUE TITLE
ACL binary support

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#111]
We use an ACL as the runtime of the ML daemon.
However, since it takes a considerable amount of time to build an ACL, I propose to provide a binary as a solution.

Four versions will be provided as follows.
- armv7a-neon
- armv7a-neon-opencl
- arm64-v8a-neon
- arm64-v8a-neon-opencl

**Comment by RedCarrottt** [comment]
How about maintain another git repository(submodule) for storing those ACL binaries?

I think that it will make ```git clone``` or ```git fetch``` a far slower.

**Comment by RedCarrottt** [comment]
I think TVM is more appropriate than ArmCL for now.

[TVM, "Optimizing Mobile Deep Learning on ARM GPU with TVM"](https://tvm.ai/2018/01/16/opt-mali-gpu)

Not only TVM documentation but also recent research papers report that TVM has greater performance than or similar one to ArmCL.

Furthermore, TVM can configure target device as not only Mali GPUs but also ARM CPUs, Nvidia GPUs, FPGAs, etc.

Therefore, introducing TVM on ANT is better than introducing vendor-specific libraries such as ArmCL.

I close this issue.
