### ISSUE TITLE
[ANT Manager] GStreamer pipeline with fixed codec

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#115]
The codec of the GStreamer pipeline is fixed to H.264.
Therefore, you need to rebuild the ANT manager if the ANT device compresses the codecs differently. 

As a result, it is necessary to improve the ANT manager to cope with various codecs.

**Comment by RedCarrottt** [comment]
It is resolved in Stream API in ANT API lite version since it can configure more flexible Gstreamer pipeline.
I close this issue.
