### ISSUE TITLE
SpMM optimization

### ISSUE THREAD

**Issue by GLeeGend** [SKKU-ESLAB/ANT#119]
"efficient sparse-matrix multi-vector product on gpus" (HPDC'18)

In this paper, DCSR format and CSR format are used in combination to apply tiling method to SpMM operation.
Even if the current performance has low sparsity, the method can be considered because it can not keep up with the GEMM operation of the dense matrix.

**Comment by RedCarrottt** [comment]
Actually, sparse matrices have a difficulties in utilizing GPU's parallelism.

This idea would enhance the performance of sparse matrix calculation in ANT's machine learning framework.

**Comment by LeeHayun** [comment]
This issue is being developed using deep learning compiler technology in the repository below.
https://github.com/SKKU-ESLAB/Auto-Compression.git

So, I close this issue.
