### ISSUE TITLE
Unable to use built-in Bluetooth module of Raspberry Pi 3

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#14]
Currently, ANT can recognize USB-connected Bluetooth modules on Raspberry Pi 3.

However, built-in Bluetooth module of Raspberry Pi 3 cannot be recognized.

I guess that this is because of bluez version problem.

**Comment by sinban04** [comment]
This is not a bug. This is because of the external bluetooth module.
When using RPI3, with the external bluetooth module, the internal bluetooth is disabled. 
So, when you are trying to use internal bluetooth, remove the external bluetooth and reboot.

Refer to issue #19
