### ISSUE TITLE
ML benchmark tool

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#143]
A standard ML benchmark tool is needed for ANT framework.
There are the following reasons
 - Measurement of execution time and memory usage when running ML job on ANT framework
 - Comparison between the latest ML frameworks

### ML framework candidates
 - [ ] ArmNN
 - [ ] TensorFlow
 - [ ] MXNet
 - [ ] PyTorch
 - [ ] Caffe

**Comment by RedCarrottt** [comment]
We have model database and kernel database in another repository. [Link](https://github.com/SKKU-ESLAB/ANT-Model-DB)
As I think, ML benchmark and kernel database are duplicated task.
I close this issue.
