### ISSUE TITLE
Segmented heap allocation of IoT.js

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#188]
Recently, I've completed to implement the segment heap allocation on IoT.js.
The segment heap allocation is also merged to [the ANT-iotjs project](https://github.com/SKKU-ESLAB/ANT-iotjs).

* https://github.com/SKKU-ESLAB/ANT-iotjs/commit/181ec3a5ec1bf9a1a610044e05f3b00aca36acc9

As now, it is not merged to the ANT main project.
It is required to merge that feature to the ANT.

**Comment by RedCarrottt** [comment]
There is a IoT.js version gap between between [ANT-iotjs repository](https://github.com/SKKU-ESLAB/ANT-iotjs) and this repository.
ANT repository uses IoT.js of newer version than ANT-iotjs repository's one.

Currently, ANT requires external module support of IoT.js.
However, since ANT-iotjs is old version, it does not support the external module.

Therefore, ANT-iotjs must be ported to newer version of IoT.js, which is currently used in ANT.

**Comment by LeeHayun** [comment]
> There is a IoT.js version gap between between [ANT-iotjs repository](https://github.com/SKKU-ESLAB/ANT-iotjs) and this repository. ANT repository uses IoT.js of newer version than ANT-iotjs repository's one.
> 
> Currently, ANT requires external module support of IoT.js. However, since ANT-iotjs is old version, it does not support the external module.
> 
> Therefore, ANT-iotjs must be ported to newer version of IoT.js, which is currently used in ANT.

I made a new issue for the issue you mentioned.
Since the issue of "segmented heap allocation" has been resolved, I close this issue.
