### ISSUE TITLE
Use of Internal Bluetooth on Raspberry Pi 3

### ISSUE THREAD

**Issue by sinban04** [SKKU-ESLAB/ANT#19]
Now, de facto standard target device of ANT is Raspberry Pi3 and Tegra TX2. 
And when we are testing on the raspberry pi3, we had some issue with the bluetooth device.
RPI3 has internal bluetooth module and it would be disabled when used with the external BT module.
This problem is general around several other projects (such as ardupilot with Navio2)
We are on testing continuously, and we will make an announcement or manual soon for RPI3 bluetooth.

Anyway, now i recommend not to use external bluetooth dongle when using RPI3.
If you have another problem, please report here. Thanks.

**Comment by RedCarrottt** [comment]
Related to #14

**Comment by RedCarrottt** [comment]
Recent selective connection disables internal Bluetooth module of Raspberry Pi 3 since the module has problems when switching between Bluetooth and Wi-fi Direct.

Therefore I close this issue.
