### ISSUE TITLE
One "require" to use ANT API

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#22]
# Problem: ```libant-message``` needs unified API binary file
Currently, ANT app should execute separated ```require()``` calls to use ANT API.

* Example) ANT app that uses both App API and Camera API
```
var appApi = require(process.env.OPEL_BIN_DIR + '/api/app-api');
var cameraApi = require(process.env.OPEL_BIN_DIR + '/api/camera-api');
```

It is because each API is implemented separately. Each API is implemented as a **separated binary**.

On the other hand, as ```libant-message``` library is introduced for IPC, message handling is handled by the ```libant-message```.

Since ```libant-message``` spawns its own message listening thread, **separated binary** makes **duplicated message listening thread**.

Therefore, API-related binary (that utilizes ```libant-message```) need to be **unified to single binary** as following example.

# Proposal: Unified API binary file & single ```require()``` call

As machine learning API will be implemented with the library, ```require``` call also should be unified to single call.

* Example) ANT app that uses both App API, Camera API and Machine Learning API
```
var antAPI = require(process.env.OPEL_BIN_DIR + '/api/ant-api');
var appAPI = new antAPI.app();
var cameraAPI = new antAPI.camera();
var mlAPI = new antAPI.ml();
```

**Comment by LeeHayun** [comment]
:clap:

**Comment by sinban04** [comment]
:+1:

**Comment by RedCarrottt** [comment]
It is sub-issue of Issue #79.
If Issue #79 is resolved, this issue will be solved also.

Therefore, I close this issue.
