### ISSUE TITLE
Unstable start when ill-coded app is installed

### ISSUE THREAD

**Issue by GH-Jo** [SKKU-ESLAB/ANT#240]
Sometimes ANT doesn't start normally.
It is terminated with this error message.

![image](https://user-images.githubusercontent.com/37430923/102710333-e6689880-42f4-11eb-8919-3b3e74d46005.png)

I figured out that it occurs after I install an ill-coded app, and restart the ANT.
I think that this makes users misunderstand that the bug is in our framework, not in the app.
We need to fix it.

**Comment by RedCarrottt** [comment]
Issue #176 and Issue #228 are related to this issue.
Separating app runtime process will resolve this problem.
