### ISSUE TITLE
ML API's image segmentation support

### ISSUE THREAD

**Issue by lee-gwang** [SKKU-ESLAB/ANT#242]
Do you have any plans to add image segmentatnion api?

**Comment by RedCarrottt** [comment]
For the image segmentation task support, we require several additional functions to the ANT framework.
As image segmentation task is used prevalently in mobile devices nowadays, adding the APIs related to image segmentation would be great.

* ML API: Image Segmentation Elements
* ML Element: Image Segmentation Elements
* Remote UI API: Functions to Display Image Segmentation Labels

**Comment by RedCarrottt** [comment]
When I implemented the object detection APIs, I've added to remote UI functions with handling the Android's custom surface view.
The image segmentation labeling function can be implemented easily, based on the object detection labeling functions.
