### ISSUE TITLE
[Question][nnstreamer] tensor_filter output dim

### ISSUE THREAD

**Issue by Podossiu** [SKKU-ESLAB/ANT#269]
Can i know the way to make a custom filter with the handmade dimension shape and data type input-output?

if i change the code of set dimension function in custom filter example, I got Tensorshape function error

**Comment by myungjoo** [comment]
Guys, you can ask directly at https://github.com/nnstreamer/nnstreamer or send emails to its mailing lists to discuss nnstreamer with its major contributors directly. You are welcomed to do so!
