### ISSUE TITLE
Open Source License Issue

### ISSUE THREAD

**Issue by sinban04** [SKKU-ESLAB/ANT#27]
Related to PR #24 , there was a discussion about the License of Open Source.
In the process of writing Travis script, i used some python scripts from Samsung/iotjs project.

In a general view, now we are using many 3rd party libraries, and
there will be many cases using other project's source code. (which allows its use)

Therefore, i think we need to discuss about the use of Open source and libraries, and
the mention of Licenses which they have.

Let's discuss about the way we mention the License of 3rd party libraries and Open Source Projects.
(Now, in case of #24 , when i use the python code of Samsung/iotjs, i added some comment to our License file)

**Comment by RedCarrottt** [comment]
As there is no comment for a while, I close this issue.
