### ISSUE TITLE
I'm finding to run ANT Daemon

### ISSUE THREAD

**Issue by kimjoohyungsd** [SKKU-ESLAB/ANT#288]
I'm new to this field. Could you elaborate on what the ANT daemon does and how it interacts with the overall framework?

**Comment by Podossiu** [comment]
Please refer to [ANT Framework 1.0 (Youtube)](https://youtu.be/AhO3crw8jro) and
Please refer to [README](https://github.com/SKKU-ESLAB/ANT/blob/master/README.md)
