### ISSUE TITLE
Test Mode of Machine Learning Daemon

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#31]
I've made test mode of machine learning daemon, as shown in PR #30.
You can use test mode of machine learning framework with following commands.
* Test Image Classifier (Camera + CNN)
  * ```sudo /etc/ant/bin/ant-ml --test-image```
* Test Motion Classifier (Accelerometer + ANN)
  * ```sudo /etc/ant/bin/ant-ml --test-motion```

The test mode can run solely, without any ANT app or daemon.

**Comment by sinban04** [comment]
We can use the image as an argument like
```
$ sudo /etc/ant/bin/ant-ml --test-image=/etc/images/cat.jpg
```
right?

**Comment by RedCarrottt** [comment]
You cannot get input from a image file. Any inference units should get input from ```InputReader``` in machine learning framework. Currently, you can get input from ```CameraInputReader``` and ```SensorInputReader```.

If you want to use image file as an input, you have to implement another  ```InputReader``` that reads image file and produces ```MLTensor```.

**Comment by sinban04** [comment]
Now, due to some environment variables, 
we should use
```
$ sudo LD_LIBRARY_PATH=/usr/local/lib ANT_DATA_DIR=/etc/ant/data /etc/ant/bin/ant-ml --test-motion
```

**Comment by RedCarrottt** [comment]
As it is announced a year ago, it is not need to announced.
I close this issue.
