### ISSUE TITLE
CMakeList.txt Build Issue

### ISSUE THREAD

**Issue by sinban04** [SKKU-ESLAB/ANT#32]
## Relative Path Issue
Currently, the CMakeList.txt files are using the relative path to the its own directory.
For example, "../../out/bin"

We need to use the environment variable to represent all the paths in our project.
E.g., ${CMAKE_SOURCE_DIR}/out/

## Build Process

Our ANT project does not support the multi-threaded compile. (-j option in make)
We should compile the frameworks step by step without multi-threading option.
It's essential to make it support multi-threaded compile to enhance the compile time.

# To-Do
- [x] Relative Path Issue
- [x] Build Process

**Comment by RedCarrottt** [comment]
:+1:

**Comment by sinban04** [comment]
#35

**Comment by sinban04** [comment]
Relative path problem has been solved in PR #39

**Comment by sinban04** [comment]
Build process problem has been solved in PR #48
