### ISSUE TITLE
ANT documentation in docs directory

### ISSUE THREAD

**Issue by sinban04** [SKKU-ESLAB/ANT#33]
In many open source projects, they are using documentation in the docs/ dir.
I think it's useful to write down some useful notes about our system.
For example, i firstly write down some useful bluetooth command in docs/bluetooth.md
I will attach the PR number later.

**Comment by sinban04** [comment]
#35

**Comment by RedCarrottt** [comment]
Nice work.

However, I'm worried that documentations in ```docs``` directory and [Github Wiki](https://github.com/SKKU-ESLAB/ANT/wiki) can be duplicated.

We need to clarify roles of two documentation locations.

**Comment by sinban04** [comment]
Yeah, right.
I think Wiki should deal with the public things like API, how to use our framework, ..
On the other hand, the docs/ dir should include some issues related to develop our framework
such as bluetooth configuration, change the appcore function or etc, ...

**Comment by RedCarrottt** [comment]
Then, let's arrange **a to-do list** about what documents we need to make.

**Comment by RedCarrottt** [comment]
As now, there are two manuals to run or modify ANT framework in `/docs`.

Also solution of issue #118 is more feasible than this solution, for this project.

Therefore, I close this issue.
