### ISSUE TITLE
Refine sample applications

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#40]
We made many changes on ANT API. For example, I changed **App API** and added **Machine Learning API**. @LeeHayun deprecated **Face Detection API**.

Therefore, we need to refine ANT sample applications in `apps/sample` directory.

Both apps use obsolete **App API** still. `SmartBB` app uses **Face Detection API** that has already deprecated.

I will update App API calls that are used in the sample apps.

**Then, how about `SmartBB` app?**

As I think, **deprecating SmartBB app and making a new machine learning app** would be good.

**Comment by sinban04** [comment]
I agree. i think we should change the sample apps totally. 
Update the samples apps after complete the tests of the new apps.

**Comment by RedCarrottt** [comment]
This job is completed and merged to mainline last year. Therefore I close this issue.
