### ISSUE TITLE
Error Handling in each framework

### ISSUE THREAD

**Issue by sinban04** [SKKU-ESLAB/ANT#43]
Now, our framework is a little fragile.
Our framework daemons could die when there were some exceptional stuffs.
We should make it resilient to make our framework sturdy.
For this, we should write some error handling code in our frameworks.
Except the fatal case that must be handled, we should have alternatives for the exceptional case.

For example, in sensor manager, 
i'm devising to make virtual sensor driver to make SENSOR daemon alive without real sensor driver.
Now, SENSOR daemon dies when there is no sensor driver file.

**Comment by RedCarrottt** [comment]
I agree with you.

I need to refine initialization procedure of Bluetooth, Wi-fi Direct connection in ```libant-cmfw```.

**Comment by RedCarrottt** [comment]
As ANT Lite deprecates old sensor framework, ANT's stability is enhanced than the ANT classic.
So I close this issue.
