### ISSUE TITLE
Integrate android branch into master branch

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#50]
ANT project is managed in two branches; `master` and `android`.

In `android` branch, there is source code of ANT manager running on companion devices(Android smartphones).
In `master` branch, there is source cod of ANT framework running on IoT devices.

Since this project is managed in separated branch, **matching binary versions on each devices is tricky**.

Therefore, I propose **integrating `android` branch into `master` branch**.

Source code inside of `android` branch can be **relocated to `android` directory in `master` branch**.

**Comment by LeeHayun** [comment]
It's a good idea.

**Comment by RedCarrottt** [comment]
We've already integrated those branches to ```master``` in PR #66.

I close this issue.
