### ISSUE TITLE
Unified Logging System

### ISSUE THREAD

**Issue by sinban04** [SKKU-ESLAB/ANT#65]
We are using independent logging system for each framework. 
However, to easily use the framework with the proper logging, it's necessary to unify our logging system.
I propose to use google's logging system 'glog' (https://github.com/google/glog)

It provides log level and several mode. 
How do you think about that?

**Comment by RedCarrottt** [comment]
There are few requirements for unified logging system.
* Easy to use (easy to link the project with `CMakeLists.txt`)
* Unified among several frameworks and libraries (communication, message)
* Categorization of each log (ex. appcore, camera, sensor, etc.)
* Multiple log levels (controllable on run-time)

Does this project meet the requirements?
