### ISSUE TITLE
Reduce the execution time of install-deps-*.sh

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#7]
Currently, ```install-deps-*.sh``` spends several hours of execution time.

This script builds all the dependent projects such as ```bluez```, ```libuv``` and ```nodejs```.

We don't need to build those projects every time.

There are several options on solution.
* Adding ```install-prebuilt-deps-*.sh``` scripts that download and install **pre-built projects**
* Replacing dependent projects with **mainline packages**(packages that can be downloaded by ```apt-get```)

**Comment by sinban04** [comment]
I agree. Some modules like node.js need to be provided as a binary. It takes too much time.

**Comment by RedCarrottt** [comment]
In the case of node.js 4.0.0, we need to provide pre-built ```*.deb``` package.

**Comment by LeeHayun** [comment]
@sinban04 @RedCarrottt 

Hi. I have another suggestion.
In ```install-deps-*.sh```, unnecessary packages exist.

Camera Framework needs ```pkg-config```, ```libdbus-1-dev```, ```glib-2.0```, ```libdbus-glib-1-dev```, ```gstreamer1.0```, ```cmake```.

What about the other frameworks?

**Comment by RedCarrottt** [comment]
@LeeHayun 
AppCore Framework needs ```glib-2.0```, ```zip```, ```cmake```, ```sqlite3``, ```libsqlite3-dev```.

```libant-cmfw``` needs ```udhcpd```, ```automake```.

```libant-message``` needs ```cmake```, ```libdbus-1-dev```, ```libdbus-glib-1-2```, ```libdbus-glib1-2-dbg```, ```libdbus-glib-1-dev```.

System server(```run_ant```) needs ```python3```.

**Comment by sinban04** [comment]
#28

**Comment by sinban04** [comment]
#26

**Comment by RedCarrottt** [comment]
I added x86-based build test process to CI system.
I prepared a docker container to boost the build test process. (#201)
I close this issue.
