### ISSUE TITLE
ODROID XU4 Support

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#70]
I plan to work with the ANT framework to support **ODROID XU4**.

To Do
---
- [ ] Add target information
  - [ ] GStreamer Pipeline configuration
  - [ ] Pre-requisite installation script
- [ ] Verify that the function is working properly

**Comment by RedCarrottt** [comment]
👍

**Comment by RedCarrottt** [comment]
@LeeHayun, it works well now, isn't it?
ANT seems to have install-deps script and camera config in [this directory](https://github.com/SKKU-ESLAB/ANT/tree/master/target/odroid-xu4).

**Comment by LeeHayun** [comment]
The issue is no longer relevant because the target dependency has been minimized in the recent ANT framework.
