### ISSUE TITLE
Upgrade the Node.js Version

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#71]
In ANT, we use **Node.js 4.x** as javascript runtime.
However, Node.js 4.x LTS Argon is no longer actively supported!

Currently, Node.js 8 LTS is recommended.
Therefore, we need to increase the version of Node.js used in ANT to 8.

For more information about release of Node.js, check the link below.
https://github.com/nodejs/Release

**Comment by RedCarrottt** [comment]
We have a plan to change ANT APIs fundamentally. #136
* Make existing ANT APIs obsolete
* Make ANT API lite version to support node.js as well

When we introduce ANT API lite version, we can implement it based on recent node.js.
Therefore I close this issue.
