### ISSUE TITLE
libuv Version Issue

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#72]
This issue is related to #71.

ANT uses libuv v1.7.5.
However, Node.js requires the latest libuv.
Because older versions do not support some functions. (e.g., `uv_os_getpid()`)

**Comment by RedCarrottt** [comment]
As I mentioned in PR #71, We have a plan to change ANT APIs fundamentally. #136
When we introduce ANT API lite version, we can implement it based on recent node.js and libuv.
Therefore I close this issue.
