### ISSUE TITLE
SpMV optimization ( sparse matrix - dense vector multiplication) - execution time

### ISSUE THREAD

**Issue by GLeeGend** [SKKU-ESLAB/ANT#74]
When the sparsity is 25%, the csr-SpMV shows the same performance as the ACL-GEMV.
It is reasonable performance?
Reason : 
- The most important factor that affects performance in the SpMV is the number of global memory accesses. When sparsity(number of non-zeros) goes up, the number of global memory access is increased numerously.

**Comment by rhkdqo93** [comment]
There was a problem with my sparse BLAS code. I've fixed it, so I'll close that issue.
