### ISSUE TITLE
SpMV optimization - reduce memory access ( SIMD-aware pruning)

### ISSUE THREAD

**Issue by GLeeGend** [SKKU-ESLAB/ANT#75]
When CSR-SpMV was 25%, it showed similar performance as ACL-GEMV.
As a result of the provisioning, the biggest cause of performance was global memory access. 
Therefore, it is effective to reduce the cache miss through regular access to the input vector and to use the SIMD-ware pruning method for reducing memory access due to CSR format characteristics.

While these problems can be solved, SIMD-aware pruning is damaging to accuracy because the pruning area is re-structible. 

Discussion
- Flex SIMD-aware pruning is proposed to complement this.
- Or Tile(4x4) based pruning

**Comment by RedCarrottt** [comment]
👍

**Comment by rhkdqo93** [comment]
Flexible group-level pruning ensures efficient use of hardware and accuracy. The cache-aware technique also enabled us to achieve this by preventing latency degradation.
