### ISSUE TITLE
ML Daemon runtime improvement

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#86]
Hi.

ANT has been using Caffe as the runtime of the ML daemon.
However, the libraries used by Caffe are not optimized for ARM devices, making it difficult to achieve good performance.
In order to achieve good ML performance in IoT devices, it is first necessary to use a good baseline library.

**Comment by RedCarrottt** [comment]
We decided to use TVM instead of Caffe and ArmCL.
I close this issue.
