### ISSUE TITLE
Sparse Matrix File Format

### ISSUE THREAD

**Issue by GLeeGend** [SKKU-ESLAB/ANT#87]
Currently, files in the MTX file format can be read in sparse matrix format. 
However, to provide real machine learning inference, you must provide an API that supports various file formats.

**Comment by LeeHayun** [comment]
First, use the sparse matrix format API provided by scipy to represent the sparse matrix. We will discuss this issue after sparse operations have been added to the ANT framework.

[https://docs.scipy.org/doc/scipy/reference/sparse.html](https://docs.scipy.org/doc/scipy/reference/sparse.html)
