### ISSUE TITLE
Model Converter for ACL

### ISSUE THREAD

**Issue by GLeeGend** [SKKU-ESLAB/ANT#88]
Currently available deep learning frameworks are typically tensorflow, caffe, pytorch, and the like. 
Using these frameworks, training a deep neural network creates a model file of each.
For example, tensorflow is a ckpt file and caffe is a caffemodel file.
To use get_weight_accessor, which is now provided in the ACL, you need to change the files like ckpt, caffemodel to npy file.

Therefore, the model converter function should be provided.

**Comment by RedCarrottt** [comment]
As we have plan to introduce TVM instead of ACL, model converter for ACL is not required.

Therefore, I close this issue.
