### ISSUE TITLE
ML plugin proposal

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#89]
Hi.

Currently, the camera framework and the ML framework are separate.
However, it is not natural. (Because doing ML can be considered as some work on the pipeline)
I propose to develop an ML plugin that can be added to the pipeline managed by the camera framework.

This idea is referenced in the following paper:
>**EdgeEye: An Edge Service Framework for Real-time Intelligent Video Analytics** (EdgeSys'18)

**Comment by RedCarrottt** [comment]
In PR #169, I added ML API based on NNStreamer and GStreamer.
I close this issue.
