### ISSUE TITLE
Using ACL for deep learning inference (SpMM)

### ISSUE THREAD

**Issue by GLeeGend** [SKKU-ESLAB/ANT#91]
In the ACL, the input matrix appears in two forms: NCHW or NHWC.
The algorithm we are currently using transposes the input matrix to the column major and proceeds to SpMM.
If you try to use this algorithm by porting to an ACL and you do not provide a matrix transpose in your ACL, you need transpose code.

**Comment by RedCarrottt** [comment]
As we have plan to introduce TVM instead of ACL, model converter for ACL is not required.

Therefore, I close this issue.
