### ISSUE TITLE
Multi GPU training  with PyTorch

### ISSUE THREAD

**Issue by hoseung2** [SKKU-ESLAB/ANT#99]
I have trouble trying to train AlexNet using Pytorch.

Using single GPU doesn't cause any problems, but using multi GPU doesn't work with the following warning message.

```
/home/khs/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py:24: UserWarning:
There is an imbalance between your GPUs. You may want to exclude GPU 2 which
has less than 75% of the memory or cores of GPU 0. You can do so by setting
the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
environment variable.
warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
```

**Comment by LeeHayun** [comment]
This issue is not related to the ANT framework. Please refer to [https://discuss.pytorch.org/t/waining-there-is-an-imbalance-between-your-gpus/17157]( https://discuss.pytorch.org/t/waining-there-is-an-imbalance-between-your-gpus/17157).
